// File Variables

// 基本
@protocol = http
@hostname = localhost
@port = 4561
@host = {{hostname}}:{{port}}
@baseUrl = {{protocol}}://{{host}}
@apiV = /v1
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@boundary = ----MyBoundary
// ENVファイルからの読み込み
@jwt = {{$dotenv AUTH_DATA_TOKEN}}
@accessToken = {{$dotenv GOOGLE_OAUTH_ACCESS_TOKEN}}
@clientId = {{$dotenv CLIENT_ID}}
@clientSecret = {{$dotenv CLIENT_SECRET}}
// 変数
@todo_group_uuid = 7ec51405-03f4-47f6-a69e-8e52395d796b
@todo_uuid =  db2d30de-127e-47cf-aa26-772398e004f4 

// Requests 

// todo新規登録
POST {{baseUrl}}{{apiV}}/todos/register HTTP/1.1
Content-Type: application/json

[
  {
    "groupHost": true,
    "userUUID": "123e4567-e89b-12d3-a456-426614174000",
    "title": "ひまぷら",
    "priority": 1
  },
  {
    "groupHost": false,
    "userUUID": "123e4567-e89b-12d3-a456-426614174000",
    "title": "バグ修正",
    "requiredTime": 5400000,
    "memo": "UIの不具合を修正する"
  }
]

# [{
#   "userUUID": "eefbacae-28b2-4e32-91be-f6c08573e6b9",
#   "title": "買い出し",
#   "priority": 3,
#   "requiredTime": 600000000000,
#   "memo": "じゃがいも忘れたら人生詰み"
# }]

### 

// todo取得(単体と親要素)
GET {{baseUrl}}{{apiV}}/todos/todos HTTP/1.1

### 

// todoGroup取得
GET {{baseUrl}}{{apiV}}/todos/todo_groups/{{todo_group_uuid}} HTTP/1.1

###

////////////////////////////認証ミドルウェア実装

// テスト
GET {{baseUrl}}/check/echo HTTP/1.1

###

// 認証ミドルウェア通過確認
GET {{baseUrl}}/check/auth HTTP/1.1
Authorization: {{jwt}}

###