// File Variables

// 基本
@protocol = http
@hostname = localhost
@port = 4561
@host = {{hostname}}:{{port}}
@baseUrl = {{protocol}}://{{host}}
@apiV = /v1
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@boundary = ----MyBoundary
// ENVファイルからの読み込み
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJfcGJfdXNlcnNfYXV0aF8iLCJleHAiOjE3MzkzNTU0OTksImlkIjoiODJtMjg0NTMzbW40bHgzIiwicmVmcmVzaGFibGUiOnRydWUsInR5cGUiOiJhdXRoIn0.4BMcNvrJkGoaC7F1V9jSKIxTkHYHG-3rdFePrb0xaM4
@accessToken = {{$dotenv GOOGLE_OAUTH_ACCESS_TOKEN}}
@clientId = {{$dotenv CLIENT_ID}}
@clientSecret = {{$dotenv CLIENT_SECRET}}
// 変数
@todo_group_uuid = 1db31e56-5b62-4c98-b951-997e49b401e1
@todo_uuid =  4e6bfebf-2a22-406a-ac56-8ba80bdfa680 

// Requests 
///////認証ミドルウェア実装

// テスト
GET {{baseUrl}}/check/echo HTTP/1.1

###

// 認証ミドルウェア通過確認
GET {{baseUrl}}/check/auth HTTP/1.1
Authorization: {{jwt}}

### todo新規登録
POST {{baseUrl}}{{apiV}}/auth/todos/register HTTP/1.1
Authorization: {{jwt}}
Content-Type: application/json

# [
#   {
#     "groupHost": true,
#     "title": "ひまぷら",
#     "priority": 1
#   },
#   {
#     "groupHost": false,
#     "title": "バグ修正",
#     "requiredTime": 5400000,
#     "memo": "UIの不具合を修正する"
#   }
# ]

[{
  "title": "wawawawawa",
  "priority": 3,
  "requiredTime": 600000000000,
  "memo": ""
}]

### todo取得(単体と親要素)
GET {{baseUrl}}{{apiV}}/auth/todos/todos HTTP/1.1
Authorization: {{jwt}}

### todoGroup取得
GET {{baseUrl}}{{apiV}}/auth/todos/todo_groups/{{todo_group_uuid}} HTTP/1.1
Authorization: {{jwt}}

### todo詳細取得
GET {{baseUrl}}{{apiV}}/auth/todos/{{todo_uuid}} HTTP/1.1
Authorization: {{jwt}}


### todo詳細取得
PUT {{baseUrl}}{{apiV}}/auth/todos/update/{{todo_uuid}} HTTP/1.1
Authorization: {{jwt}}
Content-Type: application/json

[{
  "title": "コードデバック",
  "priority": 3,
  "requiredTime": 600000000000,
  "memo": ""
}]
